const lang = {
  en: {
    home: "Home",
    diseaseIdenti: "Disease Identification",
    govtScheme: "Government Scheme",
    map: "Map",
    heading: "Krishi Unnati",
    call: "Call Us",
    plantHealthDiag: "Plant Health Diagnosis",
    checkCrop:
      "Check if your crop is healthy and find cures for crop's disease.",
    diagnosePlant: "Diagnose your plant",
    discSchemes: "Discover the latest schemes and benefits available to you",
    ourServices: "Our Services",
    about: "About",
    services: "Services",
    aboutUs: "About Us",
    contact: "Contact Us",
    plantIdenti: "PLant Identification",
    forum: "Forum",
    voiceAssist: "Voice Assistant",
    weather: "Weather Prediction",
    database: "Database Analysis",
    support: "Support",
    whatsapp: "Whatsapp",
    calll: "Call",
    sms: "SMS",
    socials: "Socials",
    linkedIn: "LinkedIn",
    twitter: "Twitter",
    insta: "Instagram",
  },
  hindi: {
    home: "होम",
    diseaseIdenti: "बीमारी की पहचान",
    govtScheme: "सरकारी योजना",
    map: "मानचित्र",
    heading: "कृषि उन्नति",
    call: "हमें कॉल करें",
    plantHealthDiag: "पौधे के स्वास्थ्य का निदान",
    checkCrop:
      "जाँचें कि आपकी फसल स्वस्थ है या नहीं और फसल की बीमारी का इलाज पाएँ।",
    diagnosePlant: "अपने पौधे का निदान करें",
    discSchemes: "आपके लिए उपलब्ध नवीनतम योजनाओं और लाभों की खोज करें",
    ourServices: "हमारी सेवाएँ",
    about: "के बारे में",
    services: "सेवाएँ",
    aboutUs: "हमारे बारे में",
    contact: "हमसे संपर्क करें",
    plantIdenti: "पौधे की पहचान",
    forum: "मंच",
    voiceAssist: "वॉयस असिस्टेंट",
    weather: "मौसम पूर्वानुमान",
    database: "डेटाबेस विश्लेषण",
    support: "सहायता",
    whatsapp: "व्हाट्सएप",
    calll: "कॉल",
    sms: "एसएमएस",
    socials: "सोशल",
    linkedIn: "लिंक्डइन",
    twitter: "ट्विटर",
    insta: "इंस्टाग्राम",
  },
};

export default lang;
